---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.alloc.nephio.org
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.alloc.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.resource.nephio.org
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.resource.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.nephio.org
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inv.nephio.org
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inv.nephio.org
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inv.nephio.org
  resources:
  - targets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inv.nephio.org
  resources:
  - targets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.resource.nephio.org
  resources:
  - ipprefixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.resource.nephio.org
  resources:
  - ipprefixes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.resource.nephio.org
  resources:
  - networkinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.resource.nephio.org
  resources:
  - networkinstances/status
  verbs:
  - get
  - patch
  - update
