apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: default
spec:
  topology: nephio
  routingTables:
  - name: default
    prefixes:
    - prefix: 1000::/64
      labels:
        nephio.org/prefix-kind: loopback
    - prefix: 192.0.0.0/16
      labels:
        nephio.org/prefix-kind: loopback
    - prefix: 2000::/32
      labels:
        nephio.org/prefix-kind: network
    - prefix: 10.0.0.0/16
      labels:
         nephio.org/prefix-kind: network
    interfaces:
    - kind: interface
      selector:
        matchLabels:
          nephio.org/purpose: infra
  
    