apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: internet
spec:
  topology: nephio
  routingTables:
  - name: internet
    prefixes:
    - prefix: 172.0.0.0/16
    - prefix: 10.0.0.0/8
      labels:
        nephio.org/nephio.org/prefix-kind: pool
    interfaces:
    - kind: bridgedomain
      name: internet # irb + cluster prefix is created here
  bridgeDomains: # per selector Key
  - name: internet
    interfaces:
    - name: all clusters
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: exists}
      attachmentType: vlan
      
    